### ISSUE TITLE
Editor Messages missing

### ISSUE THREAD

**Issue by sehaxx** [telerik/kendo-angular-messages#110]
Hello,

I can't find a list of messages for the Editor. Is it in some other repo? I got this keywords on my Editor:
![image](https://user-images.githubusercontent.com/15326428/72348297-6ac09d80-36da-11ea-978f-f306b89261a1.png)

**Comment by nevraydin** [comment]
Any progress on this issue? Some of them exists (bold, italic, underline, insertImage) but not all are completed.

**Comment by tsvetomir** [comment]
Fixed in v1.22
