### ISSUE TITLE
Error with two interpolations

### ISSUE THREAD

**Issue by nlgi** [telerik/kendo-angular-messages#14]
Hi,

kendo-translate commnd returns an error when there is message with interpolations in messages.xlf.
Sample: 
 ```
     <trans-unit id="225c24c98a62f1f8974e1c1206f6eac06d7e5b62" datatype="html">
        <source>Créé par <x id="INTERPOLATION"/> le <x id="INTERPOLATION_1"/></source>
        <target/>
        <note priority="1" from="description">Info création par qui / quand</note>
      </trans-unit>
```

Error: TypeError: Cannot read property '_' of undefined.

"INTERPOLATION_1" is the id given by ng-xi18n

Many thanks,

**Comment by tsvetomir** [comment]
Thanks for the bug report! This should be fixed in 1.7.0

**Comment by nlgi** [comment]
Hi,

In 1.7.0, same error.
If I remove this node, it works:

```
<trans-unit id="5d2bca2dfe723d964aec637df607198601d04306" datatype="html">
        <source>Créé par <x id="INTERPOLATION"/> le <x id="INTERPOLATION_1"/></source>
        <target/>
        <context-group purpose="location">
          <context context-type="sourcefile">E:/appli_client/src/app/travaux/Interventions/signalement/signalement.component.ts</context>
          <context context-type="linenumber">45</context>
        </context-group>
        <note priority="1" from="description">Info création par qui / quand</note>
      </trans-unit>
```

Note: In angular@4.1 there is a new node named 'context-group' with sourcefile attribute.
It doesn't work either if I remove 'context-group' node.

**Comment by tsvetomir** [comment]
Shouldn't be a problem. Can you share the output from `npm ls @progress/kendo-angular-messages` and `npm ls xlf-translate`? Thanks!

**Comment by nlgi** [comment]
Yes: 
`-- @progress/kendo-angular-messages@1.7.0

And:
`-- @progress/kendo-angular-messages@1.7.0
  `-- xlf-translate@2.0.0

On Windows.

I think there is an other problem.
Here is an XLF file : [http://plnkr.co/edit/sw1uoa9mGDET7BoZvJk7?p=preview](url)
Same error. If I remove last trans-unit node, it's ok.

**Comment by tsvetomir** [comment]
I've tried this in [this repo](https://github.com/tsvetomir/kendo-angular-messages-14), but it seems to be working normally. Can you please confirm?

**Comment by nlgi** [comment]
Got it: 
`node_modules\.bin\kendo-translate src\i18n\messages.xlf --locale fr-FR --force`
Result: OK

`kendo-translate src\i18n\messages.xlf --locale fr-FR --force`
Result: KO

Many thanks,

**Comment by tsvetomir** [comment]
Seems like you have an older version installed globally. Update it with `npm install -g @progress/kendo-angular-messages@1.7`
