### ISSUE TITLE
there is n't Arabic messages  locale 

### ISSUE THREAD

**Issue by kokodda** [telerik/kendo-angular-messages#23]
there is n't Arabic messages  locale    can you you prepare file or i prepare it and push it to server

**Comment by ggkrustev** [comment]
Hi @kokodda, the messages listed in this repo are a community effort. It will be great if you can contribute, translating the available messages in Arabic. 

More details on how to contribute can be found here

https://github.com/telerik/kendo-angular-messages/blob/develop/CONTRIBUTING.md

I will close this thread with this message.
