### ISSUE TITLE
run with system js 

### ISSUE THREAD

**Issue by kokodda** [telerik/kendo-angular-messages#41]
i Can't run it with system js any help how it work example or punker

**Comment by tsvetomir** [comment]
Can you share more details about the scenario you're implementing?

This package includes the messages and a CLI tool. It's not meant to be loaded at run-time.

**Comment by kokodda** [comment]
i set my locale due to  kendo angular intl  i need the messages to work with my locale in my app i use quick start structure  can  kendo messages work with system js

**Comment by tsvetomir** [comment]
Using SystemJS requires additional settings as it does not automatically discover the main package scripts. See [Using with SystemJS](http://www.telerik.com/kendo-angular-ui/components/installation/system-js/) for a detailed walk-through and a sample project.

**Comment by kokodda** [comment]
i do this all exactly but it doesn't work can provide with plunker with example working  to know the issue from me or library

**Comment by tsvetomir** [comment]
It might be more productive to fork the [kendo-angular-quickstart](https://github.com/telerik/kendo-angular-quickstart) project and add the code in question there. If the problem persist you can share the modified project with us to debug it.
