### ISSUE TITLE
kendo-translate does not work

### ISSUE THREAD

**Issue by ldzhu** [telerik/kendo-angular-messages#44]
angular/compiler [don't generate empty <target/> when extracting xliff](https://github.com/angular/angular/pull/18072) 
[when i finished step 1 and 2](http://www.telerik.com/kendo-angular-ui/components/localization/messages/#toc-translate-the-messages) , and [all steps](http://www.telerik.com/kendo-angular-ui/components/localization/messages/#toc-populate-the-translations),  file messages.es.xlf has no "target " too . It means kendo-translate doesn't work. 

If i add a "target" node manually, it works.

Please help me.

**Comment by tsvetomir** [comment]
Thanks for the heads-up. Not a change that we anticipated in any way.

Working on a fix.

**Comment by tsvetomir** [comment]
Should be fixed in [xlf-translate@2.0.1](https://github.com/tsvetomir/xlf-translate/commit/37fd49e5). Please run `npm update` to fetch the latest version.
