### ISSUE TITLE
Fix German translations for grid

### ISSUE THREAD

**Issue by m-reiseder** [telerik/kendo-angular-messages#65]
I noticed that some German translations are wrong or sound wrong in my opinion.

Here is a list how I changed them for my project:

- "kendo.grid.groupPanelEmpty": "Ziehen Sie eine Spaltenüberschrift hierher, um nach dieser Spalte zu gruppieren",
- "kendo.grid.noRecords": "Keine Datensätze verfügbar.",
- "kendo.grid.pagerFirstPage": "Zur ersten Seite",
- "kendo.grid.pagerPreviousPage": "Zur vorherigen Seite",
- "kendo.grid.pagerNextPage": "Zur nächsten Seite",
- "kendo.grid.pagerLastPage": "Zur letzten Seite",
- "kendo.grid.pagerPage": "Seite",
- "kendo.grid.pagerOf": "von",
- "kendo.grid.pagerItems": "Elementen",
- "kendo.grid.pagerItemsPerPage": "Elemente pro Seite",
- "kendo.grid.filter": "Filter",
- "kendo.grid.filterEqOperator": "ist gleich",
- "kendo.grid.filterNotEqOperator": "ist nicht gleich",
- "kendo.grid.filterIsNullOperator": "ist Null",
- "kendo.grid.filterIsNotNullOperator": "ist nicht Null",
- "kendo.grid.filterIsEmptyOperator": "ist leer",
- "kendo.grid.filterIsNotEmptyOperator": "ist nicht leer",
- "kendo.grid.filterStartsWithOperator": "beginnt mit",
- "kendo.grid.filterContainsOperator": "beinhaltet",
- "kendo.grid.filterNotContainsOperator": "beinhaltet nicht",
- "kendo.grid.filterEndsWithOperator": "endet mit",
- "kendo.grid.filterGteOperator": "ist größer als oder gleich",
- "kendo.grid.filterGtOperator": "ist größer als",
- "kendo.grid.filterLteOperator": "ist kleiner oder gleich als",
- "kendo.grid.filterLtOperator": "ist kleiner als",
- "kendo.grid.filterIsTrue": "ist richtig",
- "kendo.grid.filterIsFalse": "ist falsch",
- "kendo.grid.filterBooleanAll": "(Alle)",
- "kendo.grid.filterAfterOrEqualOperator": "ist gleich oder später als",
- "kendo.grid.filterAfterOperator": "ist später als",
- "kendo.grid.filterBeforeOperator": "ist früher als",
- "kendo.grid.filterBeforeOrEqualOperator": "ist gleich oder früher als",
- "kendo.grid.filterFilterButton": "Filtern",
- "kendo.grid.filterClearButton": "Löschen",
- "kendo.grid.filterAndLogic": "und",
- "kendo.grid.filterOrLogic": "oder",
- "kendo.grid.loading": "Laden",
- "kendo.grid.sort": "Sortieren",
- "kendo.grid.columnMenu": "Spaltenmenü",
- "kendo.grid.columns": "Spalten",
- "kendo.grid.lock": "Sperren",
- "kendo.grid.unlock": "Entsperren",
- "kendo.grid.sortAscending": "Aufsteigend sortieren",
- "kendo.grid.sortDescending": "Absteigend sortieren",
- "kendo.grid.columnsApply": "Übernehmen",
- "kendo.grid.columnsReset": "Zurücksetzen"

**Comment by tsvetomir** [comment]
Shipped in v1.14.0
