### ISSUE TITLE
Missing key for kendo.dropdownlist.noDataText

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular-messages#68]
I am missing folder dropdownlist and inside noDataText key.

**Comment by valchev** [comment]
@MaklaCof Thanks for bringing this to our attention.

I've added the missing messages for en-GB, en-US and bg-BG. You may use one of those files as a reference, to create message files for other languages.

**Comment by tapopov** [comment]
Seems to be fixed in https://github.com/telerik/kendo-angular-messages/releases/tag/v1.14.0
