### ISSUE TITLE
kendo-translate command on windows

### ISSUE THREAD

**Issue by Debug08** [telerik/kendo-angular-messages#75]
Hello,

I follow the instructions of : https://www.telerik.com/kendo-angular-ui/components/globalization/localization/messages/#toc-populating-the-translations

But when i try to launch the following command line : ./node_modules/.bin/kendo-translate src/locale/messages.fr.xlf --locale fr-FR 
I have a message : 'kendo-translate' is an unknow command.

i don't understand what i'm doing wrong...

**Comment by tsvetomir** [comment]
Thank you for reporting this issue. The example from the documentation is indeed not applicable to the Command Prompt.

The recommended syntax, starting with npm 5.2, is to use `npx`:
`npx kendo-translate src/locale/messages.fr.xlf --locale fr-FR`

For earlier npm versions you'll need to run the script using `node`:
`node ./node_modules/@progress/kendo-angular-messages/bin/kendo-translate`

**Comment by Debug08** [comment]
Thank a lot for your answer. It works fine.
