### ISSUE TITLE
French translations issues

### ISSUE THREAD

**Issue by grgouala** [telerik/kendo-angular-messages#83]
Hello,

I've noticed the following issues for French translations:

- Grid component
filter: **Filtrer**
unlock: **Débloquer**
sortAscending: **Tri croissant** (as translated in Kendo UI for JQuery instead of 'Tri ascendant')
sortDescending: **Tri décroissant** (as translated in Kendo UI for JQuery instead of 'Tri descendant')

- Date picker
toggle: **Afficher le calendrier**

- Autocomplete, combobox, dropdownlist, multiselect
noDataText: **Aucun enregistrement trouvé**
clear: **Effacer**

-Slider:
drag: **Déplacer**

-Switch
on: **Activé**
off: **Désactivé**

-Timepicker:
toogle: **Afficher le sélecteur** 

greg

**Comment by tsvetomir** [comment]
@grgouala thanks for reporting these issues. I've fixed the translations in #84 and will merge them if you don't see any problems.

**Comment by grgouala** [comment]
It's ok. You also fixed the translation issue of **filterLtOperator** that I had not noticed.
greg
